<?php

namespace Database\Seeders;

use App\Models\Genres;
use App\Models\Melody;
use App\Models\ArtistType;
use App\Models\Instrument;
use Illuminate\Database\Seeder;

class MelodySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $genres = [
            'Hip Hop',
            'Trap',
            'R&B',
            'Reggaeton',
            'Dancehall',
            'Afrobeat',
            'Drill',
            'New Jazz',
            'Moombahton',
            'Future Bass',
            'House',
            'Pop',
            'Trance',
            'Psytrance',
            'Drum and Bass',
            'Dubstep',
            'Merengue',
            'Bachata',
            'Oriental',
            'Dembow',
            'Brazilian Funk',
            'Phonk',
            'Reggae',
            'World',
        ];

        $instuments = [
            "Guitar",
            "Keys",
            "Vocals",
            "Synth",
            "Pads",
            "Plucks",
            "Synths",
            "Bass",
            "Flute",
            "Strings",
            "Brass & Woodwinds",
            "Live Sounds",
            "Ethnic",
            "World Sounds",
        ];
        
        $artistTypes = [
            "2 Chainz",
            "21 Savage",
            "6LACK",
            "A Boogie Wit da Hoodie",
            "Ace Hood",
            "Álex Rose",
            "Álvaro Díaz",
            "A\$AP Ferg",
            "Aleman",
            "Amenazzy",
            "Anuel AA",
            "Arcángel",
            "Bad Bunny",
            "Bad Gyal",
            "Becky G",
            "Big Sean",
            "Bizarrap",
            "Brray",
            "Bryant Myers",
            "Brytiago",
            "Cardi B",
            "Casper Mágico",
            "Cazzu",
            "Chencho Corleone",
            "Chief Keef",
            "Chimbala",
            "Cosculluela",
            "DaBaby",
            "Dalex",
            "Darell",
            "Daddy Yankee",
            "De La Ghetto",
            "Dei V",
            "Denzel Curry",
            "DJ Luian",
            "Don Omar",
            "Dowba Montana",
            "Duki",
            "El Alfa",
            "El Dominio",
            "Eladio Carrión",
            "Farruko",
            "Feid",
            "Fetty Wap",
            "French Montana",
            "Future",
            "Gera MX",
            "Gigolo y La Exce",
            "Gunna",
            "Guaynaa",
            "Hozwal",
            "Jack Harlow",
            "J Balvin",
            "J Cole",
            "Jay Menez",
            "Jay Wheeler",
            "Jeezy",
            "Jhay Cortez",
            "Jowell & Randy",
            "Juanka El Problematik",
            "Juicy J",
            "Justin Quiles",
            "Karol G",
            "Kanye West",
            "Kevin Gates",
            "Key Glock",
            "Kevvo",
            "Kendo Kaponi",
            "Kendrick Lamar",
            "Kiko El Crazy",
            "Kodak Black",
            "Lil Baby",
            "Lil Durk",
            "Lil Keed",
            "Lil Mosey",
            "Lil Pump",
            "Lil Tjay",
            "Lil Uzi Vert",
            "Lil Wayne",
            "Lil Yachty",
            "Lito Kirino",
            "Lunay",
            "Lyanno",
            "Maluma",
            "Manuel Turizo",
            "Mau y Ricky",
            "Meek Mill",
            "Mike Bahía",
            "Mike WiLL Made-It",
            "Migos",
            "Miky Woodz",
            "Moneybagg Yo",
            "Mora",
            "Morad",
            "Myke Towers",
            "Natti Natasha",
            "NAV",
            "NBA YoungBoy",
            "Nelly",
            "Nengo Flow",
            "Nio Garcia",
            "NLE Choppa",
            "Noriel",
            "Offset",
            "Ozuna",
            "Plan B",
            "Playboi Carti",
            "PnB Rock",
            "Polo G",
            "Pop Smoke",
            "Post Malone",
            "Pusho",
            "Quavo",
            "Rae Sremmurd",
            "Rafa Pabon",
            "Rauw Alejandro",
            "Rich the Kid",
            "Rick Ross",
            "Rod Wave",
            "Roddy Ricch",
            "Robot95",
            "Rvssian",
            "Sheck Wes",
            "Schoolboy Q",
            "Sech",
            "Ski Mask the Slump God",
            "Tainy",
            "Takeoff",
            "Tali Goya",
            "Tay-K",
            "Tempo",
            "Toosii",
            "Tory Lanez",
            "Travis Scott",
            "Trippie Redd",
            "Tyga",
            "Waka Flocka Flame",
            "Wiz Khalifa",
            "Wisin & Yandel",
            "Yaga & Mackie",
            "Yandel",
            "YBN Cordae",
            "YNW Melly",
            "Yo Gotti",
            "Young Dolph",
            "Young Nudy",
            "Young Thug",
            "Yovngchimi",
            "Zion & Lennox"
        ];
        
        
        foreach ($genres as $genre) {
            Genres::create([
                "title" => $genre,
            ]);
        }
        foreach ($instuments as $instument) {
            Instrument::create([
                "title" => $instument,
            ]);
        }
        foreach ($artistTypes as $artistType) {
            ArtistType::create([
                "title" => $artistType,
            ]);
        }
    }
}
